name: Integration test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_BASECALLING: true

    steps:
      - uses: actions/checkout@v3

      - name: Testing
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: '.tests/integration'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --sdm conda --conda-cleanup-pkgs cache'
          stagein: 'bash .tests/integration/get_resources.sh'
          show-disk-usage-on-error: true
